### ISSUE TITLE
Pointers not working

### ISSUE THREAD

**Issue by cebrax** [gregdavill/KiBuzzard#10]
I am on Windows and everything works great, except the pointers in either ends.

The error message I get when I try to have pointers in both ends or in any of the ends is:
"The system cannot find the file specified."

**Comment by gregdavill** [comment]
By pointers, do you mean `<` and `>`?

Can you send a screenshot of the label you're trying to make?

**Comment by cebrax** [comment]
Yes, here it is:

[https://i.ibb.co/d4LsFfk/Untitled.png](https://i.ibb.co/d4LsFfk/Untitled.png)

**Comment by gregdavill** [comment]
I managed to reproduce this, and it seems like `<` and `>` are used by the windows shell as special characters. They just need to be escaped with a `^` 

Can you try with the latest code?

**Comment by gregdavill** [comment]
Whoops, a typo in 32d0224b3f51b08673503970356040d9b81b05f7

But it should be fixed now.
![buzzard_et](https://user-images.githubusercontent.com/344310/105968915-980a9e80-60d7-11eb-9d31-2fd72275ff1d.PNG)

**Comment by cebrax** [comment]
Yup, fixed :) 

Thank you
