### ISSUE TITLE
Error with KiCad 8

### ISSUE THREAD

**Issue by boromyr** [gregdavill/KiBuzzard#110]
```py
Errore KiCad

[Content]
Traceback (most recent call last):
  File "D:\Users/PC/Documents/KiCad/8.0/scripting\plugins\com_github_gregdavill_KiBuzzard\plugin.py", 
	line 93, in run_buzzard
    io = pcbnew.PCB_PLUGIN()
         ^^^^^^^^^^^^^^^^^
AttributeError: module 'pcbnew' has no attribute 'PCB_PLUGIN'

```
When I try to modify an existing label, I get this error. I tried to search for `PCB_PLUGIN` in pcbnew.py of version 8 of KiCad and I believe it has been replaced with `PCB_IO`.

Windows 11 
KiCad 8 RC2
KiBuzzard https://github.com/gregdavill/KiBuzzard/commit/207b9701f8974d12ba3a5e0ece8fa42601168edd

**Comment by arturo182** [comment]
Can confirm in `8.0.0-rc2-253-g7e194d5f69` on Windows 11

![image](https://github.com/gregdavill/KiBuzzard/assets/249082/113b3aee-5034-4266-9049-5004b6f1f8a9)

Only affects editing, can still add new labels.

**Comment by boromyr** [comment]
Solved, just replace `io = pcbnew.PCB_PLUGIN()` with `io = pcbnew.PCB_IO_KICAD_SEXPR()`
