### ISSUE TITLE
Mirror functions don't work with labels

### ISSUE THREAD

**Issue by ipmcc** [gregdavill/KiBuzzard#116]
Mirroring functions, represented by these buttons...

<img width="135" alt="Screen Shot 2024-03-24 at 8 02 23 AM" src="https://github.com/gregdavill/KiBuzzard/assets/537077/8b1c11b7-7769-498d-9789-f077e9ba9488">

...do not work with labels created in KiCad 8.0.0, and a KiBuzzard HEAD pull at hash 4194a2dc.

When you click those buttons, simply nothing happens. There's not even anything added to the Undo stack.

**Comment by gregdavill** [comment]
This seems like a KiCad issue, as these mirror buttons do not work on other regular footprints.

You can flip a footprint to back layer with 'F', but that also swaps the layer.
