### ISSUE TITLE
Scale textbox in the new GUI doesn't work

### ISSUE THREAD

**Issue by VedantParanjape** [gregdavill/KiBuzzard#13]
The scale input box doesn't seem to work as expected. It doesn't take float input, nor does it set to 0.04 by default.

CC: @arturo182

**Comment by arturo182** [comment]
Please provide more info, because it works for me:
![kicad](https://user-images.githubusercontent.com/249082/106595898-8bad9800-6554-11eb-877d-c92f2b4e787e.gif)

**Comment by VedantParanjape** [comment]
Here's the video: https://streamable.com/0ls78m

I am trying to port this to kicad-5.1.9. With your GUI, the command window works fine. If I set scale to anything other than 0, it works fine.

**Comment by arturo182** [comment]
Hmm, what if you try changing the 0 [here](https://github.com/gregdavill/KiBuzzard/blob/main/KiBuzzard/dialog/dialog_base.py#L74) to 2, maybe this is less enforced on Windows. If that works, let me know and I'll make a proper fix commit including the wx form file.

**Comment by VedantParanjape** [comment]
@arturo182 Yes, this fixed it. But then default value of the text input is 1.0 and not 0.04 (in the code you have set it to 0.04)

**Comment by VedantParanjape** [comment]
> Hmm, can you retest with [1a434df](https://github.com/gregdavill/KiBuzzard/commit/1a434df84a6e8f05c83d2fb65a1d81af1b110e15), that should fix the default value too, otherwise maybe try to delete the config.ini and see if after that the default value works. It should be saved between plugin calls.

This worked fine, just one issue.

![Screenshot from 2021-02-02 23-04-53](https://user-images.githubusercontent.com/22630228/106639572-1c16c780-65ab-11eb-915c-9fd291fb24d1.png)

I am unable to see the selected brackets in Label drop box

**Comment by DCelectronics** [comment]
I have the same issue with KiCad v5.1.9 on Linux only (Win10 is OK).
I implemented fix https://github.com/gregdavill/KiBuzzard/commit/1a434df84a6e8f05c83d2fb65a1d81af1b110e15 but I changed it to 2 decimal places for consistency with the default behaviour in Win10 (besides 0.001 is too fine step).

**Comment by gregdavill** [comment]
It might be nice to have the scale setup in nicer units, like mm or mils.

Right now it's a bit disconnected, is it supposed to be inches? Buzzard doesn't really make this clear.

**Comment by DCelectronics** [comment]
I believe it is in inches for the text height.
