### ISSUE TITLE
Wish: Multiple Lines

### ISSUE THREAD

**Issue by cebrax** [gregdavill/KiBuzzard#17]
Is it possible to have multiple lines of text?

**Comment by Spirit532** [comment]
Would also be nice to be able to specify multiple labels with certain pitch, to make arrays.

**Comment by gregdavill** [comment]
Fixed by #39 

![Screenshot from 2021-04-19 11-49-06](https://user-images.githubusercontent.com/344310/115172955-6c5ee980-a105-11eb-92ff-0274b6bb8f08.png)
