### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by reportingsjr** [gregdavill/KiBuzzard#19]
I've just cloned this repo into the 5.99 plugins directory using the command in the readme.

When clicking the button to launch the plugin in pcbnew, I get the following error:
![image](https://user-images.githubusercontent.com/244912/108607470-9eb2cb80-738e-11eb-8681-20e8a718ebdb.png)

This using the fedora nightly, updated just an hour ago.

Kicad build settings:
![image](https://user-images.githubusercontent.com/244912/108607553-141e9c00-738f-11eb-8dbf-c8d5150388c9.png)

Python version info:
[jon@arikem dev]$ python3 --version
Python 3.8.7

**Comment by gregdavill** [comment]
Can you open a scripting console in pcbnew and run this:

```python
>>> import wx
>>> [print(x.GetTitle()) for x in wx.GetTopLevelWindows()]
```

For reference I get the following:
```
>>> [print(x.GetTitle()) for x in wx.GetTopLevelWindows()]
meiji-led-ring — KiCad 5.99

meiji-led-ring — Pcbnew

KiCAD:PCBNEW - Python Shell - PyAlaMode 0.9.8
[None, None, None, None, None]
```

**Comment by reportingsjr** [comment]
`[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Startup script executed: /home/jon/.config/kicad/5.99/PyShell_pcbnew_startup.py

import wx
[print(x.GetTitle()) for x in wx.GetTopLevelWindows()]
obsidian-boa-r0.1 — KiCad 5.99
obsidian-boa-r0.1 — PCB Editor

KiCAD:PCBNEW - Python Shell - PyAlaMode 0.9.8
[None, None, None, None]
`

**Comment by gregdavill** [comment]
Interesting your pcbnew window comes with the title `PCB Editor` 

Easy enough to add that to the check: https://github.com/gregdavill/KiBuzzard/commit/e9f754c75a3555868efbd4b453abd4b32fbaa6c2

**Comment by arturo182** [comment]
I just updated my nightly and ran into the exact same issue, guess they changed the title recently.

**Comment by arturo182** [comment]
Here's the change 4 days ago: https://gitlab.com/kicad/code/kicad/-/commit/66b33834b5f5f44150080aed645037ebd9f3eee3#83a257d25158f354cabcb709bdd360a2778ca729_173_173

**Comment by reportingsjr** [comment]
Yep, that fixed it! Thanks Greg!
