### ISSUE TITLE
Label with space and angle bracket does not show correct

### ISSUE THREAD

**Issue by ifadiga** [gregdavill/KiBuzzard#21]
Hi,
I use KiBuzzard plugin with KiCad 5.99 nightly and have a problem when using the angle bracket, with space before or after the text in the label.
In the picture is shown that I get arrow character before or after the text when using space and sometimes label not show correct (created a square polygon, instead of angle polygon on start). 

![image](https://user-images.githubusercontent.com/49251350/109431855-d1049e80-7a08-11eb-8ad4-ad3d73d4cea5.png)

**Comment by putyn** [comment]
@ifadiga you are most likely using windows, right ? I have a pull request #24 that will hopefully fix it 😄 just waiting for it to be merged.

**Comment by ifadiga** [comment]
@putyn thanks for the reply.
Yes, I am using Windows.
Ok, I had fixed it to label what I need.

**Comment by gregdavill** [comment]
Can you try the latest version? I have a feeling this is resolved now with the new UI changes.
Feel free to open up a new issue if you're having issues.
