### ISSUE TITLE
wx related errors when using KiCad 5.99 nightly macOS

### ISSUE THREAD

**Issue by robin7331** [gregdavill/KiBuzzard#27]
When running KiBuzzard on the KiCad 5.99 nightly macOS build I get a lot of `wx` related issues. 
They all seem to occur from the `dialog_text_base.py` file which is auto-generated by the `wxFormBuilder`.

**_Afaik this KiCad version ships with wx version 3.0._**

Had to call `wx.StockGDI._initStockObjects()` to initialize all the `wx.{{color}}` calls before using them. 

Next, I had to remove all the `SetToolTip` calls because of : 
```
File "/Users/robin/Library/Preferences/kicad/5.99/scripting/plugins/KiBuzzard/KiBuzzard/dialog/dialog_text_base.py", line 69, in __init__
self.m_MultiLineText.SetToolTip( _(u"Enter the text placed on selected layer.") )

File "/private/var/folders/0_/50zzr6qs1v90gkw4sg2qkfph0000gn/T/AppTranslocation/F288DBE0-034A-47DA-BC08-B40B1802B0B5/d/KiCad.app/Contents/Frameworks/python/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 11394, in SetToolTip
return _core_.Window_SetToolTip(*args, **kwargs)

TypeError: in method 
```

It's still not working though and I suspect its a wx version incompatibility issue.

**Comment by gregdavill** [comment]
I think there are some troubles with wx versions across KiCad 5.1 and 5.99 and Win/OSX/Linux.

You're in 5.99 right? if you refresh via Prefs->Action Plugins then you can see a log if you hit any errors.

I generally just run `python KiBuzzard/test_dialog.py' to test UI changes.

**Comment by robin7331** [comment]
Yes I am on 5.99. 

![Screenshot 2021-04-11 at 10 56 16](https://user-images.githubusercontent.com/3868463/114298034-8d478f00-9ab4-11eb-9615-43be5d9c4c4f.png)

When I refresh the Action Plugins KiBuzzard simply disappears from the list. 
No error dialog or logs in the scripting console. 🤔

**Comment by robin7331** [comment]
Did you fix the `SetSizeHintsSz` directly in the file or by changing some property in your `wxFormBuilder` ?

**Comment by gregdavill** [comment]
Yes, I did that one directly. 

Ideally it would be fixed in wxFormBuilder. But the version that supports wx3.0 pre-dates github, and it on sourceforge.

**Comment by robin7331** [comment]
The thing is how to deal with this incompatibility? 
(re)do it entirely in wx3.0? 
Is that even compatible with newer versions? Or is it then working on macOS KiCad but incompatible with others?

**Comment by robin7331** [comment]
The funny thing is. I think `SetSizeHintsSz` is not even a implemented in wx 3.0.4.
At least I cannot find it. It's not on the `wxDialog` or any of its super classes 🤷‍♂️

**Comment by robin7331** [comment]
I managed to get the dialog open. But I do not see a preview.
![Screenshot 2021-04-11 at 11 38 14](https://user-images.githubusercontent.com/3868463/114299229-7e63db00-9aba-11eb-9d61-c37d8ced461f.png)

If I paste something onto the canvas after hitting 'ok' I only get this cross.
![Screenshot 2021-04-11 at 11 40 08](https://user-images.githubusercontent.com/3868463/114299281-b0753d00-9aba-11eb-8caf-b8863142d8b2.png)

It seems to be empty of some sort
![Screenshot 2021-04-11 at 11 41 16](https://user-images.githubusercontent.com/3868463/114299317-ddc1eb00-9aba-11eb-8f1c-584d7ae6314c.png)

Somethings missing...

**Comment by gregdavill** [comment]
Can you run KiCad from a terminal to see it's output? Might let me know if you're hitting an error.

**Comment by robin7331** [comment]
When launching from the terminal I can't even open the `*.kicad_pcb` file. 
I get this error:

![Screenshot 2021-04-11 at 11 46 43](https://user-images.githubusercontent.com/3868463/114299469-ae5fae00-9abb-11eb-9d3e-f02d0a9bfb48.png)

But that's not really KiBuzzard related I guess.

**Comment by gregdavill** [comment]
Can you try the latest commit? I'm not catching the exceptions now. 
So if you hit one it should show a popup I think.

**Comment by gregdavill** [comment]
Latest commit will output a traceback if there is an exception in generating the preview.

The "preview" actually generates the polys needed by the footprint, so it's not surprising that your footprint was empty.

![Screenshot from 2021-04-11 19-44-22](https://user-images.githubusercontent.com/344310/114300263-86de0500-9afe-11eb-9cde-45ab11e950f7.png)

**Comment by gregdavill** [comment]
I've also removed a `SetToolTip` call, and added a thin shim class 'DialogShim' so we can deal with `SetSizeHintsSz` automatically without manual change of the generated code.

**Comment by robin7331** [comment]
The `DialogShim` seems to have an error.

![Screenshot 2021-04-11 at 12 18 50](https://user-images.githubusercontent.com/3868463/114300330-14e6cb00-9ac0-11eb-896c-4c6d97ef9118.png)

**Comment by gregdavill** [comment]
Sorry, try now.
Also, thanks for helping debug this on OSX. :)

**Comment by robin7331** [comment]
Lets make it happen :)
There still are a few tool tips you might have forgotten to remove 🤓
![Screenshot 2021-04-11 at 12 24 09](https://user-images.githubusercontent.com/3868463/114300493-d4d41800-9ac0-11eb-87e7-3ea6c01850b3.png)

![Screenshot 2021-04-11 at 12 23 30](https://user-images.githubusercontent.com/3868463/114300483-cede3700-9ac0-11eb-9089-f33d6f4d4b21.png)d

Also I had to modify the `StartOnce` call to the `wx.Timer`.
For some reason it did not like this one.
Thankfully `self.timer.Start(milliseconds=250, oneShot=True)` does the same thing. 

PR submitted 👋

**Comment by gregdavill** [comment]
Might need to be careful with `Start` instead of `StartOnce`. But useful to know that we need to avoid 'StartOnce'.

**Comment by gregdavill** [comment]
Whoops, I'm blind. 
I see you're also got `OnShot=True`. So no functional difference.

**Comment by robin7331** [comment]
According to [here](https://docs.wxwidgets.org/3.0.4/classwx_timer.html#a8df981f7075786811598828af1d294ac) `StartOnce` is only a wrapper for `Start` with the wxTIMER_ONE_SHOT parameter.
