### ISSUE TITLE
Preview error on Windows

### ISSUE THREAD

**Issue by gregdavill** [gregdavill/KiBuzzard#31]
Default window shows no preview of text
![Screenshot 2021-04-12 164806](https://user-images.githubusercontent.com/344310/114355988-3d99be00-9baf-11eb-8c6c-07149728dfd7.png)

However if you scale the same window you can start to see the rendered text.
Not sure if this is a layering issue, or axis/alignment issue.
![Screenshot 2021-04-12 164829](https://user-images.githubusercontent.com/344310/114356099-5f934080-9baf-11eb-87af-b7fb92f5d5b0.png)

**Comment by CaptClaude** [comment]
Datapoint: MacOS 10.14.6 / KiCad Version: (5.1.6-0-10_14), release build does not exhibit this behavior. Freshly installed on 4/13/2021.
<img width="776" alt="KiBuzzard 2021-04-13 at 10 43 28 PM" src="https://user-images.githubusercontent.com/19495272/114651677-0825cb00-9caa-11eb-9e7f-10ff5d5e7f2d.png">

**Comment by gregdavill** [comment]
Nice thanks! 

I suspect it's a quirk on windows.

Unrelated note the font kerning could use a bit of work. the `.` in `1.5` isn't very centered.

**Comment by CaptClaude** [comment]
Also, notice that the dash ("-") is shown as if it were an underscore ("_"). If you want, I can post what all the various fonts look like on my system. Not all of them are useful, but this is a gigantic step forward from the last version I tried. Anything I can do to help, because this is super useful.

**Comment by gregdavill** [comment]
Yep, I did notice that. I've just opened #37 to track that issue.

I think I see the issue in the way we're rendering characters from freetype.

**Comment by gregdavill** [comment]
Fixed with c3ba570 

![Screenshot 2021-04-14 155657](https://user-images.githubusercontent.com/344310/114663967-3a7f0900-9d3a-11eb-9f80-b6498afc9ac3.png)
