### ISSUE TITLE
Settings are not stored or correctly loaded when reopening the dialog

### ISSUE THREAD

**Issue by robin7331** [gregdavill/KiBuzzard#32]
It would be nice if the settings would be stored to disk when closing the dialog with `Ok`. 
Right now I have to reenter every value when I like to do many similar labels. 

I see `loadConfig()` and `saveConfig()` I the `dialog.py` file. 
I may misinterpret their intended behavior but if those are supposed to store/load those settings it may be a bug.
Because that is not working on my machine. 

@gregdavill is that a bug or is there nothing like that implemented?

**Comment by gregdavill** [comment]
You're right, there are those functions.

They should work as you describe, but they're not 100% connected and working yet.

**Comment by robin7331** [comment]
Alright. Just wanted to make sure.
So this is also not working properly on your side? Or is it a macOS thing again?
Might look into it today and submit a PR if I get it to work.

**Comment by gregdavill** [comment]
Hopefully this commit will fix this :)

**Comment by robin7331** [comment]
Indeed! ✌️
