### ISSUE TITLE
Font kerning is handled incorrectly

### ISSUE THREAD

**Issue by gregdavill** [gregdavill/KiBuzzard#37]
Here is an example of input text `AaBb_- [efg]`

![Screenshot from 2021-04-14 14-36-08](https://user-images.githubusercontent.com/344310/114657254-d3a82280-9d2e-11eb-8708-a9fe85c13ac4.png)

When rendered with GIMP, it looks like this:
![gimp_text](https://user-images.githubusercontent.com/344310/114657434-36012300-9d2f-11eb-8929-72468a447a17.png)

You can see there are various glyph placement differences.

**Comment by CaptClaude** [comment]
So my "dash rendered as underscore" issue on MacOS is clearly not a **_Windows_** quirk.

**Comment by gregdavill** [comment]
Sorry, I was referring to the preview appearing blank, as a windows quirk. (Appears to be painting below a 'wx.frame')

The kerning issues are a real bug and not OS dependent.

**Comment by gregdavill** [comment]
Fixed by #39
