### ISSUE TITLE
Layer option

### ISSUE THREAD

**Issue by tjstyle** [gregdavill/KiBuzzard#43]
Thanks for developing this plug-in!
I just want to ask for an enhancement option, can KiBuzzard generate other than on the "F.SilkS' or 'B.SilkS' layer?
Sometimes I use label/polygon on the "F.Mask" layer above the copper pour.

Regards,
TJ.

**Comment by elekgeek** [comment]
I agree, sometimes on copper it is also required.

**Comment by gregdavill** [comment]
Layers are implemented now https://github.com/gregdavill/KiBuzzard/pull/73
![Screenshot from 2022-02-23 10-15-17](https://user-images.githubusercontent.com/344310/155238860-64530edd-cee8-4f6b-8256-c4e0b3f7ca22.png)
