### ISSUE TITLE
5.99: "Not in schematic" attribute should probably be set

### ISSUE THREAD

**Issue by alexvlockwood-bes** [gregdavill/KiBuzzard#46]
Since the labels are pasted directly into the layout, they don't correspond to anything in the schematic, and thus usually get deleted on the next sch→pcb sync. If "Not in schematic" is set, they are kept.

**Comment by gregdavill** [comment]
I agree! This is only an option in 5.99 though right? Along with `exclude from BOM` which probably also makes sense for these logos.

A quick work-around is to make sure `Delete footprints with no symbols` is not checked when updating the PCB.
![Screenshot from 2021-05-08 09-48-41](https://user-images.githubusercontent.com/344310/117519463-c0613d80-afe2-11eb-8d90-6f7aabcf55fa.png)

**Comment by gregdavill** [comment]
It looks like we're originally using `(attr virtual)` which was being extended to the newer v6 syntax of `(attr exclude_from_pos_files exclude_from_bom)`

On v6 the labels should new be using: `(attr board_only exclude_from_pos_files exclude_from_bom)`
