### ISSUE TITLE
Cannot get it to work on KiCad 5.1.5 and Windows 10

### ISSUE THREAD

**Issue by stuartpittaway** [gregdavill/KiBuzzard#48]
Hello, I cannot get the plugin to appear in KiCad 5.1.5 (Win 10)

kibuzzard.log is generated but is zero bytes

The plugin doesn't appear in the list of plugins in PCB NEW.

Any suggestions on debugging?

**Comment by stuartpittaway** [comment]
Ignore this, works on 5.1.10 +

**Comment by gregdavill** [comment]
Thanks for the feedback! 

I'd say we're only going to be supporting the latest stable release (+ nightly). Updating to 5.1.10 would have been my first suggestion.
