### ISSUE TITLE
"Assertion error" crash

### ISSUE THREAD

**Issue by shurik179** [gregdavill/KiBuzzard#51]
I tried installing this on my machine and it crashed:
![image](https://user-images.githubusercontent.com/12883611/122572354-a96b2d80-d01b-11eb-8130-046480dafd13.png)

KiCad 5.99 nightly, Windows10: 

Application: KiCad PCB Editor (64-bit)

Version: (5.99.0-10557-g64afa3a42e), release build

Libraries:
	wxWidgets 3.1.4
	libcurl/7.74.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: May 12 2021 21:01:58
	wxWidgets: 3.1.4 (wchar_t,STL containers)
	Boost: 1.75.0
	OCC: 7.5.0
	Curl: 7.74.0-DEV
	ngspice: 34
	Compiler: Visual C++ 1928 without C++ ABI

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=ON
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
	KICAD_SCRIPTING_ACTION_MENU=ON
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by Bouni** [comment]
I've got similar erros whil developing a plugin. I found that after a crash a KiCad process keeps running despite no open windows.
Killing those tasks and starting KiCad again fixed these sort of issues for me.
