### ISSUE TITLE
Practical improvements

### ISSUE THREAD

**Issue by yuyubades** [gregdavill/KiBuzzard#52]
In the other options we have <>,/ \ on right and left, pls add also ) ( for right and left

**Comment by tylercrumpton** [comment]
Aren't those already there? I was able to use ( and ) the other night.

**Comment by gregdavill** [comment]
Can you provide a visual example of what you would like these end cap options to look like?

One reason for not having `)` `(` options is that these would need to protrude quite a bit, and I'm not sure how useful they would actually be to people. I'd rather not pollute the options with label caps that are never used.
