### ISSUE TITLE
KiBuzzard labels trip warning for "duplicate footprints"

### ISSUE THREAD

**Issue by alexvlockwood-bes** [gregdavill/KiBuzzard#53]
KiCad 5.99 now throws a warning for duplicate footprints on DRC if multiple footprints have the same reference. This would be easily avoided by appending a unique ID to each label created.

**Comment by gregdavill** [comment]
This sounds reasonable. 

I've added a hex timestamp to the end of the footprint name, does this fix the DRC issues?

**Comment by alexvlockwood-bes** [comment]
Works great! Thank you.
