### ISSUE TITLE
"D" in "GND" disappears when using Cap right ")"

### ISSUE THREAD

**Issue by alextsam** [gregdavill/KiBuzzard#54]
I encountered the following bizarre issue:

When creating a GND label with the following settings, the result is missing the "D" letter. This does not happen if the character is lowercase (or any other character) or if the cap right is something else than ")".

![image](https://user-images.githubusercontent.com/4224959/126052180-6d42ea9a-e3fa-4ff5-9edc-f65b9e3f0042.png)

![image](https://user-images.githubusercontent.com/4224959/126052182-3f0ec86f-97af-4115-a48f-7b8dbcb41b85.png)

**Comment by gregdavill** [comment]
Interesting indeed.
I can re-create this here, looks like the object isn't correctly cutting out the outer `D` shape. But all the paths are there if you turn on outline mode.

![Screenshot from 2021-07-18 10-39-40](https://user-images.githubusercontent.com/344310/126052635-6ce046a1-6e4b-4697-8038-7a0c383d4cea.png)

I'll look into why this might be. 

In the mean-time you can manually work-around, by editing the footprint and moving the one of the control points on the bottom left of the `D`.
![Screenshot from 2021-07-18 10-43-02](https://user-images.githubusercontent.com/344310/126052665-57f57a60-be95-45b9-8166-660734af85ef.png)

**Comment by alextsam** [comment]
The manual workaround works well, thanks!

By the way, here is another case I have encountered, in case it helps with researching the root cause. This time, the "H" in "CHG" has the same issue, with left cap "(" and right cap ")":

![image](https://user-images.githubusercontent.com/4224959/126053362-9bd142cf-6b44-446c-859b-2afecad37d9b.png)

**Comment by gregdavill** [comment]
Seems like this was fixed at some point... I can't reproduce this anymore
Please open up a new issue if you can repo with newest commit.
