### ISSUE TITLE
Folder name of Buzzard is conflicting

### ISSUE THREAD

**Issue by VedantParanjape** [gregdavill/KiBuzzard#6]
Folder name of Buzzard in deps is "buzzard" and I added my fork of Buzzard in deps, and now it's capital buzzard.

Any way to normalize this?

**Comment by gregdavill** [comment]
If you want to change it to lower case. 
Delete the current `deps/Buzzard`.
Re-add with a lowercase `git submodule add https://github.com/VedantParanjape/KiBuzzard deps/buzzard`

**Comment by VedantParanjape** [comment]
Worked
