### ISSUE TITLE
Does not show up after install on Windows 10?

### ISSUE THREAD

**Issue by gcsalzburg** [gregdavill/KiBuzzard#62]
Hi Greg! I followed the steps to install on Windows 10, but I don't see anything when I "Refresh plugins" in KiCad.
The menu is just blank there.

Here you can see where it is installed. Are there any other steps to get it to appear?

![image](https://user-images.githubusercontent.com/32631912/144256877-1c82bdd2-3e92-4960-9429-f1af405c461b.png)

Thanks,
George

**Comment by arturo182** [comment]
It should be inside the `scripting` directory. Also best way to make sure plugins are reloaded is to close KiCad and start it again, and not just eeschema or pcbnew, the main KiCad window.

**Comment by gcsalzburg** [comment]
Great - that works perfectly now!
Sorry for the stupid question :)

**Comment by arturo182** [comment]
No problem, enjoy :)
