### ISSUE TITLE
Ghost/zombie label when deleting an edited label

### ISSUE THREAD

**Issue by gregdavill** [gregdavill/KiBuzzard#74]
## Bug Description

When attempting to delete a label that's been edited, the graphics of the logo remain, even though you can no longer select it without using a box selection.

## Steps to reproduce
1. Create Label with KiBuzzard
2. Select label, repoen KiBuzzard.
3. Edit text/layer/size. Click OK.
4. Label is updated, now select and delete the label.
5. **Bug: Label graphics remain

**Comment by gregdavill** [comment]
I think this might have been caused by issuing a `pcbnew.Refresh()` call within the plugin logic, that's been removed in [af9c5e9](https://github.com/gregdavill/KiBuzzard/commit/af9c5e93f9fc4eacdbb585496f890b034d71330b) 

Running [af9c5e9](https://github.com/gregdavill/KiBuzzard/commit/af9c5e93f9fc4eacdbb585496f890b034d71330b)  I can no longer reproduce.

**Comment by elekgeek** [comment]
Thank you for your time, indeed!

Look at this video, FSilk.S has an issue that you will spot on the fly. 
Also this issue happens when, for example editing the label and changing the alignment

At the end, closing PCB Editor crashes and KiCAD main window closes by itself, thu main window should not close when closing PCB editor.. So, the ghost issue is kinda resolved, but crashing is not, sorry man. 

I am really glad we have layers options now, really thanks for all contributors!

https://user-images.githubusercontent.com/8074127/153710699-b187f7a7-4d4f-45a4-bfd7-d6bb4dab1660.mp4

**Comment by gregdavill** [comment]
Not sure we can work-around this. I've put in a commit to KiCad that seems to fix the segfault issue. 

KiCad's python bindings have a "SwapData" function that can swap data between two footprints, which avoids us deleting a footprint, avoiding the bug. But this appears to break Undo/Redo, resulting in a segfault if you try to undo after editing a footprint.

**Comment by elekgeek** [comment]
Yes, I noticed the undo/redo issue while recording the video, I excluded it as I was unable to specify the error cause, so I removed it from the video uploaded here.

Thanks 🙏

**Comment by gregdavill** [comment]
> Look at this video, FSilk.S has an issue that you will spot on the fly, the label is kinda outlined, look @ 00:06 in the video.
Also this issue happens when, for example editing the label and changing the alignment

This should be fixed with [7c3dc33](https://github.com/gregdavill/KiBuzzard/commit/7c3dc332ca4e1ffed54732bcd11803736b14a7e6) It was just an issue that the label generation wasn't being passed the correct layer, so it was creating a label on `Edge.Cuts` which looks like that because filed shapes on `Edge.Cuts` don't really make sense.

I think I'll remove the Edge.Cuts layer option actually.

**Comment by gregdavill** [comment]
My KiCad patch has been merged, and will appear in 6.0.3 release. 

This will fix KiCad from crashing on close, after editing a footprint. 
(KiCad Bug: https://gitlab.com/kicad/code/kicad/-/issues/10827)
