### ISSUE TITLE
Width option has some problems

### ISSUE THREAD

**Issue by liborw** [gregdavill/KiBuzzard#80]
Hi,

first thanks for this plugin! I have found couple of problems with the width option. The label is always a bit wider than set width and also the caps are not taken into account, both combined makes it quite hard align labels.
![2022-04-27-112140_2560x1410_scrot](https://user-images.githubusercontent.com/132918/165486783-d3be80f9-c049-40e6-8033-a4065f930079.png)

**Comment by gregdavill** [comment]
Thanks for taking a bit of a deeper look at this. 

I kind of tweaked some scaling factors a bit so the widths kinda matched up to mm. But it looks like it's a bit off.
Different end caps also will always increase the width currently.
