### ISSUE TITLE
6.04 - Windows 11 - No label is generated.

### ISSUE THREAD

**Issue by MariusHeier** [gregdavill/KiBuzzard#82]
Its me from Twitter. OS info in the topic.

**Comment by MariusHeier** [comment]
This is my CTRL V output, but nothing happends.

(module kibuzzard-626E85A5 (layer F.Cu) (tedit 626E85A5)
  (attr board_only exclude_from_pos_files exclude_from_bom)
  (descr "Converted using: scripting")
  (tags svg2mod)
  (fp_text reference kibuzzard-626E85A5 (at 0 -2.051425708333) (layer F.SilkS) hide
    (effects (font (size 0.00025400000000000005 0.00025400000000000005) (thickness 2.5400000000000002e-06)))
  )
  (fp_text value G*** (at 0 2.051425708333) (layer F.SilkS) hide
    (effects (font (size 0.00025400000000000005 0.00025400000000000005) (thickness 2.5400000000000002e-06)))
  )
  (fp_poly
    (pts 
      (xy -8.208168429285 -2.050917708347)
      (xy -7.898605929285 -1.4716125)
      (xy -6.322218429285 -1.4716125)
      (xy -5.769768429285 1.4430375)
      (xy -5.769768429285 -1.4335125)
      (xy -5.393530929285 -1.4906625)
      (xy -5.064918429285 -1.50495)
      (xy -4.786907491785 -1.48351875)
      (xy -4.533899679285 -1.419225)
      (xy -4.311848116785 -1.3090921875)
      (xy -4.126705929285 -1.15014375)
      (xy -3.978473116785 -0.941784375)
      (xy -3.867149679285 -0.68341875)
      (xy -3.797498116785 -0.3708796875)
      (xy -3.774280929285 -0.0)
      (xy -3.799879366785 0.3792140625)
      (xy -3.876674679285 0.69770625)
      (xy -3.998713741785 0.9590484375)
      (xy -4.160043429285 1.1668125)
      (xy -3.455193429285 1.31445)
      (xy -3.283743429285 0.8382)
      (xy -2.976562179285 0.981075)
      (xy -2.778323116785 1.03108125)
      (xy -2.540793429285 1.04775)
      (xy -2.295524679285 1.01679375)
      (xy -2.140743429285 0.93106875)
      (xy -2.062162179285 0.80724375)
      (xy -2.040730929285 0.66675)
      (xy -2.093118429285 0.504825)
      (xy -2.226468429285 0.37861875)
      (xy -2.407443429285 0.27860625)
      (xy -2.607468429285 0.1952625)
      (xy -2.883693429285 0.085725)
      (xy -3.143249679285 -0.0714375)
      (xy -3.336130929285 -0.30718125)
      (xy -3.412330929285 -0.657225)
      (xy -3.345060616785 -1.02631875)
      (xy -3.143249679285 -1.304925)
      (xy -2.941372595939 -1.434570833347)
      (xy -2.694516345939 -1.512358333347)
      (xy -2.402680929285 -1.5382875)
      (xy -2.148482491785 -1.522809375)
      (xy -1.928812179285 -1.476375)
      (xy -1.588293429285 -1.3382625)
      (xy -1.759743429285 -0.885825)
      (xy -2.024062179285 -1.000125)
      (xy -2.359818429285 -1.04775)
      (xy -2.619110095939 -1.010179166653)
      (xy -2.774685095939 -0.897466666653)
      (xy -2.826543429285 -0.7096125)
      (xy -2.778918429285 -0.55959375)
      (xy -2.657474679285 -0.44529375)
      (xy -2.490787179285 -0.3571875)
      (xy -2.307430929285 -0.28575)
      (xy -2.019299679285 -0.16906875)
      (xy -1.743074679285 0.00238125)
      (xy -0.726280929285 -0.0333375)
      (xy 0.578644070715 -0.0333375)
      (xy 1.283494070715 -0.0047625)
      (xy 1.300162820715 -0.3661171875)
      (xy 1.350169070715 -0.67865625)
      (xy 1.433512820715 -0.9423796875)
      (xy 1.550194070715 -1.1572875)
      (xy 1.752864904061 -1.368954166653)
      (xy 2.005277404061 -1.495954166653)
      (xy 2.307431570715 -1.5382875)
      (xy 2.614348237368 -1.49621875)
      (xy 2.868348237368 -1.3700125)
      (xy 3.069431570715 -1.15966875)
      (xy 3.184029226965 -0.945505078125)
      (xy 3.265884695715 -0.6816328125)
      (xy 3.314997976965 -0.368051953125)
      (xy 3.331369070715 -0.0047625)
      (xy 3.314997976965 0.360759375)
      (xy 3.265884695715 0.676275)
      (xy 5.026819070715 0.6096)
      (xy 4.986337820715 0.38338125)
      (xy 4.824412820715 0.20716875)
      (xy 4.479131570715 0.09286875)
      (xy 4.220765945715 0.0625078125)
      (xy 3.893344070715 0.0523875)
      (xy 3.936206570715 -0.3434953125)
      (xy 3.969544070715 -0.73104375)
      (xy 3.994547195715 -1.1078765625)
      (xy 4.012406570715 -1.4716125)
      (xy 5.517356570715 -1.4716125)
      (xy 5.517356570715 -0.9858375)
      (xy 4.502944070715 -0.9858375)
      (xy 4.479131570715 -0.66675)
      (xy 4.455319070715 -0.3952875)
      (xy 4.815681570715 -0.346604166653)
      (xy 5.109369070715 -0.251354166653)
      (xy 5.336381570715 -0.1095375)
      (xy 5.497777404061 0.0777875)
      (xy 5.594614904061 0.3095625)
      (xy 5.626894070715 0.5857875)
      (xy 5.555456570715 0.96440625)
      (xy 5.336381570715 1.266825)
      (xy 5.170884695715 1.381125)
      (xy 5.931694070715 1.476375)
      (xy 6.072187820715 1.1668125)
      (xy 6.169819070715 0.97869375)
      (xy 6.276975320715 0.7762875)
      (xy 6.391870633215 0.5637609375)
      (xy 6.512719070715 0.34528125)
      (xy 6.634162820715 0.1279921875)
      (xy 6.750844070715 -0.0809625)
      (xy 5.979319070715 -1.4716125)
      (xy 6.612731570715 -1.4716125)
      (xy 7.079456570715 -0.5286375)
      (xy 7.569994070715 -1.4716125)
      (xy 8.160544070715 -1.4716125)
      (xy 7.408069070715 -0.09525)
      (xy 7.535465945715 0.1143)
      (xy 7.660481570715 0.333375)
      (xy 7.780139383215 0.5542359375)
      (xy 7.891462820715 0.76914375)
      (xy 7.992070633215 0.97393125)
      (xy 8.079581570715 1.16443125)
      (xy 8.208169070715 1.476375)
      (xy 7.574756570715 1.476375)
      (xy 7.474148758215 1.220390625)
      (xy 7.353300320715 0.9382125)
      (xy 7.219355008215 0.6429375)
      (xy 7.079456570715 0.3476625)
      (xy 6.941344070715 0.6340078125)
      (xy 6.803231570715 0.93106875)
      (xy 6.674644070715 1.2186046875)
      (xy 6.565106570715 1.476375)
      (xy 5.931694070715 1.476375)
      (xy 5.170884695715 1.381125)
      (xy 4.969669070715 1.46685)
      (xy 4.732734695715 1.520428125)
      (xy 4.460081570715 1.5382875)
      (xy 4.226719070715 1.524)
      (xy 3.998119070715 1.48828125)
      (xy 3.800475320715 1.438275)
      (xy 3.664744070715 1.3858875)
      (xy 3.783806570715 0.9001125)
      (xy 4.050506570715 0.9953625)
      (xy 4.232672195715 1.027509375)
      (xy 4.455319070715 1.038225)
      (xy 4.738687820715 1.000125)
      (xy 4.914900320715 0.90249375)
      (xy 5.003006570715 0.7667625)
      (xy 5.026819070715 0.6096)
      (xy 3.265884695715 0.676275)
      (xy 3.184029226965 0.941784375)
      (xy 3.069431570715 1.1572875)
      (xy 2.868348237368 1.368954166653)
      (xy 2.614348237368 1.495954166653)
      (xy 2.307431570715 1.5382875)
      (xy 2.000514904061 1.495954166653)
      (xy 1.746514904061 1.368954166653)
      (xy 1.545431570715 1.1572875)
      (xy 1.430833914465 0.941784375)
      (xy 1.348978445715 0.676275)
      (xy 1.299865164465 0.360759375)
      (xy 1.283494070715 -0.0047625)
      (xy 0.578644070715 -0.0333375)
      (xy 0.578644070715 0.542925)
      (xy -0.726280929285 0.542925)
      (xy -0.726280929285 -0.0333375)
      (xy -1.743074679285 0.00238125)
      (xy -1.535905929285 0.26908125)
      (xy -1.475184054285 0.4494609375)
      (xy -1.454943429285 0.6715125)
      (xy -1.522213741785 1.0388203125)
      (xy -1.724024679285 1.31206875)
      (xy -1.934368429285 1.437745833347)
      (xy -2.206624679285 1.513152083347)
      (xy -2.540793429285 1.5382875)
      (xy -2.870596554285 1.5186421875)
      (xy -3.126580929285 1.45970625)
      (xy -3.455193429285 1.31445)
      (xy -4.160043429285 1.1668125)
      (xy -4.358282491785 1.3233796875)
      (xy -4.591049679285 1.43113125)
      (xy -4.853582491785 1.4936390625)
      (xy -5.141118429285 1.514475)
      (xy -5.448299679285 1.49780625)
      (xy -5.769768429285 1.4430375)
      (xy -6.322218429285 -1.4716125)
      (xy -6.322218429285 0.4905375)
      (xy -6.335910616785 0.698896875)
      (xy -6.376987179285 0.89535)
      (xy -6.557962179285 1.228725)
      (xy -6.702623116785 1.3567171875)
      (xy -6.884193429285 1.45494375)
      (xy -7.105649679285 1.5174515625)
      (xy -7.369968429285 1.5382875)
      (xy -7.645002804285 1.5192375)
      (xy -7.870030929285 1.4620875)
      (xy -8.208168429285 1.27635)
      (xy -7.984330929285 0.809625)
      (xy -7.720012179285 0.9572625)
      (xy -7.422355929285 1.0287)
      (xy -7.215782491785 0.9983390625)
      (xy -7.053262179285 0.90725625)
      (xy -6.947891866785 0.7340203125)
      (xy -6.912768429285 0.4572)
      (xy -6.912768429285 -0.9858375)
      (xy -7.898605929285 -0.9858375)
      (xy -7.898605929285 -1.4716125)
      (xy -8.208168429285 -2.050917708347)
      (xy -8.720798637632 -2.050917708347)
      (xy -8.921823726437 -2.041041978995)
      (xy -9.120912833751 -2.011509899653)
      (xy -9.316148622674 -1.962605880391)
      (xy -9.505650865748 -1.894800893604)
      (xy -9.68759455285 -1.808747938409)
      (xy -9.860227466768 -1.705275751835)
      (xy -10.021887058159 -1.585380827518)
      (xy -10.171016456845 -1.450217819213)
      (xy -10.306179465149 -1.301088420527)
      (xy -10.426074389427 -1.139428829136)
      (xy -10.529546576041 -0.966795915218)
      (xy -10.615599531236 -0.784852228116)
      (xy -10.683404518023 -0.595349985042)
      (xy -10.732308537285 -0.400114196158)
      (xy -10.761840616627 -0.201025088805)
      (xy -10.771716345978 -0.0)
      (xy -10.761840616627 0.201025088805)
      (xy -10.732308537285 0.400114196158)
      (xy -10.683404518023 0.595349985042)
      (xy -10.615599531236 0.784852228116)
      (xy -10.529546576041 0.966795915218)
      (xy -10.426074389427 1.139428829136)
      (xy -10.306179465149 1.301088420527)
      (xy -10.171016456845 1.450217819213)
      (xy -10.021887058159 1.585380827517)
      (xy -9.860227466768 1.705275751835)
      (xy -9.68759455285 1.808747938409)
      (xy -9.505650865748 1.894800893604)
      (xy -9.316148622674 1.962605880391)
      (xy -9.120912833751 2.011509899653)
      (xy -8.921823726437 2.041041978995)
      (xy -8.720798637632 2.050917708347)
      (xy -8.208168429285 2.050917708347)
      (xy 8.208169070715 2.050917708347)
      (xy 8.720799279061 2.050917708347)
      (xy 8.921824324885 2.041041920059)
      (xy 9.120913384216 2.011509790155)
      (xy 9.316149121387 1.962605729102)
      (xy 9.505651310208 1.894800709494)
      (xy 9.687594941748 1.808747730526)
      (xy 9.860227800063 1.705275529109)
      (xy 10.021887337083 1.58538059864)
      (xy 10.17101668362 1.450217592439)
      (xy 10.306179643187 1.301088203635)
      (xy 10.426074523095 1.139428629111)
      (xy 10.529546670537 0.96679573845)
      (xy 10.615599592593 0.784852079962)
      (xy 10.683404552908 0.595349869948)
      (xy 10.732308552922 0.400114117498)
      (xy 10.761840620556 0.201025048919)
      (xy 10.771716345978 -0.0)
      (xy 10.761840620556 -0.201025048919)
      (xy 10.732308552922 -0.400114117498)
      (xy 10.683404552908 -0.595349869948)
      (xy 10.615599592593 -0.784852079963)
      (xy 10.529546670537 -0.96679573845)
      (xy 10.426074523095 -1.139428629111)
      (xy 10.306179643187 -1.301088203635)
      (xy 10.17101668362 -1.450217592439)
      (xy 10.021887337083 -1.58538059864)
      (xy 9.860227800063 -1.705275529109)
      (xy 9.687594941748 -1.808747730526)
      (xy 9.505651310208 -1.894800709494)
      (xy 9.316149121387 -1.962605729102)
      (xy 9.120913384216 -2.011509790155)
      (xy 8.921824324885 -2.041041920059)
      (xy 8.720799279061 -2.050917708347)
      (xy 8.208169070715 -2.050917708347)
      (xy -8.208168429285 -2.050917708347)
    )
    (layer F.SilkS)
    (width 0.0)
  )
  (fp_poly
    (pts 
      (xy 2.802731570715 -0.0047625)
      (xy 2.574131570715 -0.0523875)
      (xy 2.500312820715 0.16906875)
      (xy 2.312194070715 0.2619375)
      (xy 2.116931570715 0.16906875)
      (xy 2.045494070715 -0.0523875)
      (xy 2.116931570715 -0.276225)
      (xy 2.312194070715 -0.371475)
      (xy 2.500312820715 -0.276225)
      (xy 2.574131570715 -0.0523875)
      (xy 2.802731570715 -0.0047625)
      (xy 2.788708654061 -0.314589583347)
      (xy 2.746639904061 -0.570970833347)
      (xy 2.676525320715 -0.77390625)
      (xy 2.521148758215 -0.9721453125)
      (xy 2.307431570715 -1.038225)
      (xy 2.096690945715 -0.9721453125)
      (xy 1.940719070715 -0.77390625)
      (xy 1.869281570715 -0.570970833347)
      (xy 1.826419070715 -0.314589583347)
      (xy 1.812131570715 -0.0047625)
      (xy 1.826419070715 0.307710416653)
      (xy 1.869281570715 0.565679166653)
      (xy 1.940719070715 0.76914375)
      (xy 2.096690945715 0.9673828125)
      (xy 2.307431570715 1.0334625)
      (xy 2.521148758215 0.9673828125)
      (xy 2.676525320715 0.76914375)
      (xy 2.746639904061 0.565679166653)
      (xy 2.788708654061 0.307710416653)
      (xy 2.802731570715 -0.0047625)
    )
    (layer F.SilkS)
    (width 0.0)
  )
  (fp_poly
    (pts 
      (xy -5.183980929285 1.000125)
      (xy -5.131593429285 1.0048875)
      (xy -5.079205929285 1.0048875)
      (xy -4.743449679285 0.9286875)
      (xy -4.524374679285 0.7191375)
      (xy -4.405312179285 0.40243125)
      (xy -4.378523116785 0.2101453125)
      (xy -4.369593429285 -0.0)
      (xy -4.398168429285 -0.371475)
      (xy -4.498180929285 -0.6905625)
      (xy -4.693443429285 -0.91201875)
      (xy -5.012530929285 -0.9953625)
      (xy -5.098255929285 -0.99298125)
      (xy -5.183980929285 -0.981075)
      (xy -5.183980929285 1.000125)
    )
    (layer F.SilkS)
    (width 0.0)
  )
)

**Comment by gregdavill** [comment]
Did you install via the KiCad Plugin & content manager?

Can you try installing version 1.1.0? 

![Screenshot from 2022-05-02 15-28-29](https://user-images.githubusercontent.com/344310/166191035-c73f6de3-1ce4-4549-bd20-d9891f327316.png)

**Comment by MariusHeier** [comment]
1.1.0 works fine: ) Thanks

**Comment by gregdavill** [comment]
Great! :)
