### ISSUE TITLE
can make support fusion 360 ?

### ISSUE THREAD

**Issue by Witawat** [gregdavill/KiBuzzard#85]
can make support fusion 360 ?

thankyou

**Comment by gregdavill** [comment]
This plugin was based on [Buzzard](https://github.com/sparkfunX/Buzzard), a sparkfun plugin for CadSoft Eagle, since Fusion Electronics is the evolution of Eagle, it might be best to ask there. I'm not sure how Fusion handles plugins.

This plugin will only target KiCad.
