### ISSUE TITLE
Add option to add "inverse"

### ISSUE THREAD

**Issue by ijl-bitsa** [gregdavill/KiBuzzard#93]
Any chance of adding an option  "inverse" ?  So that text appears as positive on a PCB layer and not inverted in a "bordered" box ?

An option to change aspect ration, height and width of the font would be usefull too ?

**Comment by duckyb** [comment]
To get the regular text without the box just remove the caps

![image](https://user-images.githubusercontent.com/27895007/200080618-d08caf4e-ea48-4216-ac66-1dd0540eb6bf.png)

![image](https://user-images.githubusercontent.com/27895007/200080726-83b333a6-8642-4377-8ea5-770cce296750.png)
