### ISSUE TITLE
Feature: Add support for bars over text

### ISSUE THREAD

**Issue by FromenActual** [gregdavill/KiBuzzard#97]
SparkFun's Buzzard plugin allows for bars over text to indicate inverted pins, [here's an example](https://www.sparkfun.com/products/19895) product with a couple inverted labels (MCS and ACS):

![image](https://user-images.githubusercontent.com/11908506/204716840-1fc81b1b-4821-4edc-b8a5-4d4962bef712.png)

Far as I can tell, there's no way to do it with KiBuzzard yet:

![image](https://user-images.githubusercontent.com/11908506/204715916-839316e4-b1cb-4ddc-9333-71fcce37d2d3.png)

Would be a great addition for feature parity!

**Comment by ilium007** [comment]
Would be great to see this in the original plugin!

**Comment by gregdavill** [comment]
This is now a feature thanks to #108 

![image](https://github.com/gregdavill/KiBuzzard/assets/344310/1e39a7c4-114a-4853-bd7d-f73480d0e715)
